version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # location of your package.json
    schedule:
      interval: "weekly" # checks once a week
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "Peer-de-Bakker"
    assignees:
      - "Peer-de-Bakker"
    versioning-strategy: "increase"
